#!/bin/bash

# 서버 실시간 감지 프로세스 수동 시작 가이드
echo "🚀 서버 실시간 감지 프로세스 시작 가이드"
echo ""
echo "다음 명령어를 서버에서 직접 실행하세요:"
echo ""
echo "1. 서버 접속:"
echo "   ssh gojaehyun@baburger.xyz"
echo ""
echo "2. 작업 디렉토리 이동:"
echo "   cd /var/www/html"
echo ""
echo "3. 기존 프로세스 정리:"
echo "   sudo pkill -f \"node index.js watch\" || true"
echo ""
echo "4. 테스트 실행:"
echo "   node index.js generate"
echo ""
echo "5. 실시간 감지 서비스 시작:"
echo "   sudo systemctl enable obsidian-blog"
echo "   sudo systemctl start obsidian-blog"
echo ""
echo "6. 서비스 상태 확인:"
echo "   sudo systemctl status obsidian-blog"
echo ""
echo "7. 실시간 로그 확인:"
echo "   sudo journalctl -u obsidian-blog -f"
echo ""
echo "📋 서비스 관리 명령어:"
echo "  - 상태 확인: sudo systemctl status obsidian-blog"
echo "  - 서비스 중지: sudo systemctl stop obsidian-blog"
echo "  - 서비스 재시작: sudo systemctl restart obsidian-blog"
echo "  - 로그 확인: sudo journalctl -u obsidian-blog -f"
echo ""
echo "🌐 웹사이트: https://baburger.xyz"
echo "📡 RSS 피드: https://baburger.xyz/rss.xml"
echo "🗺️ 사이트맵: https://baburger.xyz/sitemap.xml"
echo ""
echo "✅ 설정 완료 후 이 맥을 끄셔도 서버에서 계속 실행됩니다!" 